title: Sanjay Vonk
logo: /assets/img/headshot.jpeg
email: 615985sv@student.eur.nl
github_username: sanjayvonk
#description: Minimal is a theme for GitHub Pages.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
