title: Sanjay Vonk
logo: /assets/img/headshot.jpeg
use_text_title: True
theme: jekyll-theme-minimal

# title: Sanjay Vonk
# logo: /assets/img/headshot.jpeg
# #description: Contact: Sanjay.Vonk@outlook.com
# #show_downloads: true
# theme: jekyll-theme-minimal
